---

# This is a sample Inventory file for the ZDP Installer Ansible Playbooks
# The topology (what service goes where is setup here.) is for a 4 node ZDP deployment with HA architecture
# zdpnode3 and zdpnode4 are gateway nodes to hadoop cluster(hive, mr and spark clinets deployed)
# Variables specific to an installation go to vars.yml. Secrets go to vault.yml

# Don't forget the the ':' at the end of each hostname
all:
  vars:
    ansible_user: centos # change only if not being deployed on a machine with OS other than CentOS
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    mysql:
    cdh:
      vars:
        ansible_become: true
      children:
        cdh_servers:
          children:
            utility_servers:
            gateway_servers:
              vars:
                host_template: HostTemplate-Gateway 
                role_ref_names: HDFS-HTTPFS-1
            master_servers:
                children:
                    cdh_master1:
                      vars:
                        host_template: HostTemplate-Master1
                    cdh_master2:
                      vars:
                        host_template: HostTemplate-Master2
                    cdh_master3:
                      vars:
                        host_template: HostTemplate-Master3
            worker_servers:
        utility_servers:
          children:
            scm_server:
            db_server:
            krb5_server:
    zdp:
      children:
        registry:
        es:
        gateway:
        activemq:
        logstash:
        kibana:
        lineage:
        ingestionwarden:
        executor:
        hive:
        mr:
        spark:
        dme:
